services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: esapptest-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123!
    ports:
      - "1433:1433"
    volumes:
      - esapptest_sql_data:/var/opt/mssql

volumes:
  esapptest_sql_data:
